### ISSUE TITLE
Criar um  app django

### ISSUE THREAD

**Issue by lamenezes** [opensanca/maoaberta#13]
Para deixar mais modularizado podemos, inicialmente, criar esses apps django:
- `contributors`:  responsável por contribuidores (responsáveis de ongs e apoiadores de projetos/ongs), 
- `organizations`: responsável por ongs/instituições, 
- `projects`: responsável por projetos, necessidades, etc.

O que acham dessa divisão?

**Comment by lucasmatheustesta** [comment]
criando app "projetos".

**Comment by lamenezes** [comment]
@lucasmatheustesta atualizei a descrição \o

**Comment by lucasmatheustesta** [comment]
done.
